env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false 
}

render {
	new_render_scheduling = true
}

source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/animation.conf
source = ~/.config/hypr/config/borders.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/input.conf

