exec-once = swaybg -i ~/.config/hypr/wallpapers/photo_2026-02-04_22-20-55.jpg
exec = waybar &
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
